title: Oliver Dai
logo: nice pic//Mugen-half.jpeg

show_social: true
show_excerpts: false
show_frame: true
show_sidebar: false

description: "Finance Ph.D. Student at Carlson School of Management"

external:
  - {title: Mail, icon: envelope, url: "mailto:dai00191@umn.edu"}
  - {title: Linkedin, icon: linkedin, url: www.linkedin.com/in/wenbao-dai"}
  - {title: Twitter, icon: twitter, url: "https://x.com/Oliver_Dai_Econ"}
  
theme: jekyll-theme-minimal

